:rotating_light: fix require-each-key
Fix frontend/src/routes/meals/[year]-[month]-[day]/+page.svelte:
  Error: 45:6 Each block should have a key (svelte/require-each-key)